kind: BuildConfig
apiVersion: apps/v1
metadata:
  name: "build-cara-nginx"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/testcara/tekton-triggers-learning"
  strategy:
  dockerStrategy:
    dockerfilePath: Dockerfile
  output:
    to:
      kind: "ImageStreamTag"
      name: "cara/cara-hello-nginx:latest"
