apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  labels:
    app: hello-nginx
  namespace: default
spec:
  ports:
  - nodePort: 31153
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: hello-nginx
  sessionAffinity: None
  type: NodePort
